
spring:
  application:
    name: Java Spring Data Mongo Service

  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:jsds;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: embedded

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    use_sql_comments: true
    format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

  h2:
    console:
      enabled: true
      path: /jsdms-console

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    order: 0

  mongodb:
    host: localhost
    port: 27017
    database: mongo_app
    uri: mongodb://node1:27017,node2:27017,node3:27017/?replicaSet=comments&retryWrites=true
    # spring.data.mongodb.uri=mongodb://username:password@node1:27017,username:password@node2:27017,username:password@node3:27017/?replicaSet=comments&retryWrites=true


#  mvc:
#    dispatch-options-request: true

application:
  info:
    name: ${spring.application.name}
    base-package: com.morrie.tutorials.jsdms
    version:
      major: "v1"
      full: "v1.0.0"

server:
  port: 9980

logging:
  config: classpath:logback.xml
  level:
    org.springframework: INFO
    org.hibernate: INFO
    springfox.documentation: INFO
    com.zaxxer: INFO
